In [300]:
# Dependencies
import os.path
import json
import pandas as pd
import urllib.request, json

In [301]:
# List the urls for the necessary JSON files
cia_2016 = "https://raw.githubusercontent.com/iancoleman/cia_world_factbook_api/master/data/2017-12-25_factbook.json"
cia_2015 = "https://raw.githubusercontent.com/elyselam/CryptoPortfolio/master/2016-12-26_factbook.json"
cia_2014 = "https://raw.githubusercontent.com/elyselam/CryptoPortfolio/master/2015-12-28_factbook.json"
cia_2013 = "https://raw.githubusercontent.com/elyselam/CryptoPortfolio/master/2014-12-29_factbook.json"
cia_2012 = "https://raw.githubusercontent.com/elyselam/CryptoPortfolio/master/2013-12-30_factbook.json"
cia_2011 = "https://raw.githubusercontent.com/elyselam/CryptoPortfolio/master/2012-12-31_factbook.json"
cia_2010 = "https://raw.githubusercontent.com/elyselam/CryptoPortfolio/master/2011-12-26_factbook.json"
cia_2009 = "https://raw.githubusercontent.com/elyselam/CryptoPortfolio/master/2010-12-27_factbook.json"
url_list = [cia_2009, cia_2010, cia_2011, cia_2012, cia_2013, cia_2014, cia_2015, cia_2016]

In [302]:
# Create dictionaries to capture desired data
cia_countries = {}
country_desired = ["world","united_states"]

In [303]:
# Create a DataFrame
cia_dataframe = pd.DataFrame()

In [305]:
# Loop through the JSON by desired country and extract desired data for the new dicitonary
for each_url in url_list:
    with urllib.request.urlopen(each_url) as url:
        factfile = json.loads(url.read().decode())
    for country in country_desired:
        data_items = factfile["countries"][country]["data"]
        cia_countries = {
            "Country Name": factfile["countries"][country]["data"]["name"],
            "Year": int(data_items["economy"]["gdp"]["purchasing_power_parity"]["annual_values"][0]["date"]),
            "Population": int(data_items["people"]["population"]["total"]),
            "GDP": int(data_items["economy"]["gdp"]["purchasing_power_parity"]["annual_values"][0]["value"]),
            "GDP per Capita": int(data_items["economy"]["gdp"]["per_capita_purchasing_power_parity"]\
                                        ["annual_values"][0]["value"]),
            "GDP Real Growth Rate": float(data_items["economy"]["gdp"]["real_growth_rate"]["annual_values"][0]["value"]),
            "Unemployment Rate": float(data_items["economy"]["unemployment_rate"]["annual_values"][0]["value"]),
            "Inflation Rate": float(data_items["economy"]["inflation_rate"]["annual_values"][0]["value"]),
            }
        cia_dataframe = cia_dataframe.append(pd.DataFrame(cia_countries, index=[0]), ignore_index=True)

In [307]:
# Order the columns, sort the rows, and then reindex the dataframe
cia_ordered_df = cia_dataframe[["Country Name", "Year", "Population", "GDP", "GDP per Capita",\
                                 "GDP Real Growth Rate", "Inflation Rate", "Unemployment Rate"]]
cia_sorted_df = cia_ordered_df.sort_values(by=["Country Name", "Year"])
cia_sorted_df.reset_index(inplace=True)
cia_sorted_df

,index,Country Name,Year,Population,GDP,GDP per Capita,GDP Real Growth Rate,Inflation Rate,Unemployment Rate
0,1,United States,2009,310232863,14120000000000,46000,-2.6,-0.3,9.3
1,3,United States,2010,313232044,14660000000000,47200,2.8,1.6,9.6
2,5,United States,2011,313847465,15080000000000,48300,1.8,3.1,9.0
3,7,United States,2012,316668567,15940000000000,50700,2.2,2.1,8.1
4,9,United States,2013,318892103,16719999999999,52800,1.6,1.5,7.3
5,11,United States,2014,321368864,17350000000000,54400,2.4,1.6,6.2
6,13,United States,2015,323995528,17950000000000,55800,2.4,0.1,5.3
7,15,United States,2016,326625791,18620000000000,57600,1.5,1.3,4.9
8,0,World,2009,6768181146,70170000000000,10400,-0.7,0.0,8.7
9,2,World,2010,6928198253,74540000000000,11200,4.9,2.5,8.7
10,4,World,2011,7021836029,79390000000000,11900,3.7,5.0,9.1
11,6,World,2012,7095217980,84970000000000,12700,3.0,4.1,9.0
12,8,World,2013,7174611584,87250000000000,13100,2.9,3.9,8.4
13,10,World,2014,7256490011,109300000000000,16400,3.3,3.8,8.3
14,12,World,2015,7323187457,114200000000000,15700,3.0,3.6,8.3
15,14,World,2016,7405107650,120200000000000,16400,3.0,4.6,7.8